### ISSUE TITLE
自定义播放器

### ISSUE THREAD

**Issue by HQAmenghen** [JimHans/bgm.res#1]
除了内置的mpv，能否在播放时使用自定义的播放器如potplayer等

**Comment by JimHans** [comment]
以后会支持的，现在这个功能正在跟别的功能一起开发，未来版本将支持直接用用户在系统里默认配置的播放器打开，但由于现在的首页动态背景需要读取内置mpv的播放记录才能定位截图，所以如果用自定义播放器的话，这个功能估计到时候就不能用了，只能给内置mpv情况用😥，其他功能不会受影响

**Comment by zh970677996** [comment]
希望未来还可以考虑支持下弹弹play这样的播放器，我还是挺喜欢看多源（B站+动画疯）弹幕追番的，不过感觉不太容易搞

**Comment by linyaocrush** [comment]
同求这个功能，我用内置的播放器不知道为什么会卡卡的

**Comment by JimHans** [comment]
0.17.1版本已经支持直接使用系统配置的默认播放器播放，可以更新看看效果
