### ISSUE TITLE
不能正确打开文件夹，qBittorrnet Web UI地址无法保存

### ISSUE THREAD

**Issue by skytree2181301** [JimHans/bgm.res#2]
版本：v0.16.1
### 不能正确打开文件夹
"媒体库"中选择番剧，点击"打开文件夹"，打开的目录是"C:\Users\用户名\Documents"。包括在"设置"-"实验室"-"打开内置mpv配置文件"，点击"点击打开"后，也是进入"C:\Users\用户名\Documents"目录。
### qBittorrnet Web UI地址无法保存
在"设置"-"设定qBittorrnet Web UI地址"中填写地址，点击保存图标后，弹出"设置完成，刷新或重启客户端生效。实际上刷新后"设定qBittorrnet Web UI地址"变为”AutoUpdateMediaInfo“，在"实验室"-"打开设置配置文件"，修改行 "LocalStorageqBittorrnetURL": "AutoUpdateMediaInfo" 为qBittorrnet Web UI地址并保存，刷新客户端，可以正确保存"设定qBittorrnet Web UI地址"，并加载做种界面。但是此时如果点击"设定qBittorrnet Web UI地址"处的保存按钮，"设定qBittorrnet Web UI地址"又会变为”AutoUpdateMediaInfo“。(最开始"设定字幕文件夹(暂不可用)"和"设定qBittorrnet Web UI地址"都是“default”,后来不知到做了什么都变成”AutoUpdateMediaInfo“了）。

**Comment by JimHans** [comment]
关于没办法打开番剧文件夹的问题，这个估计跟文件夹名称有关系，部分文件夹内的特殊符号可能导致解码错误。可否提供一下你需要打开的文件夹名称与路径，我这边好做一下复现。
第二个问题是提交函数获取数据链接到上面字幕文件夹那个输入框去了，之前自用也没查出来，我的锅:( 已修复，下个版本合入

**Comment by skytree2181301** [comment]
我媒体库中的所有番剧都有打开文件夹目录不正确的问题，下面列出了一些路径
设定媒体库目录：E:/ACG/Anime
作品URL：
E:/ACG/Anime\2024夏季番组\败犬女主太多了
E:/ACG/Anime\2012春季番组\[T.H.X&VCB-Studio] Hyouka [Ma10p_1080p]
E:/ACG/Anime\2023夏季番组\[Nekomoe kissaten&LoliHouse] BanG Dream! It’s MyGO!!!!! [01-13][WebRip 1080p HEVC-10bit AAC]
E:/ACG/Anime\2024春季番组\GIRLS BAND CRY
E:/ACG/Anime\2014春季番组\[Snow-Raws]ノーゲーム・ノーライフ
E:/ACG/Anime\2023春季番组\为美好的世界献上爆炎！

我将名为"test.mp4"的文件放在目录"E:\ACG\Anime\test"下，bgm.res扫描改动加入媒体库，作品URL：E:/ACG/Anime\test，点击打开文件夹依然出现问题。

以上所有情况，打开文件夹都会进入"C:\Users\用户名\Documents"目录。

**Comment by JimHans** [comment]
> 我媒体库中的所有番剧都有打开文件夹目录不正确的问题，下面列出了一些路径 设定媒体库目录：E:/ACG/Anime 作品URL： E:/ACG/Anime\2024夏季番组\败犬女主太多了 E:/ACG/Anime\2012春季番组[T.H.X&VCB-Studio] Hyouka [Ma10p_1080p] E:/ACG/Anime\2023夏季番组[Nekomoe kissaten&LoliHouse] BanG Dream! It’s MyGO!!!!! [01-13][WebRip 1080p HEVC-10bit AAC] E:/ACG/Anime\2024春季番组\GIRLS BAND CRY E:/ACG/Anime\2014春季番组[Snow-Raws]ノーゲーム・ノーライフ E:/ACG/Anime\2023春季番组\为美好的世界献上爆炎！
> 
> 我将名为"test.mp4"的文件放在目录"E:\ACG\Anime\test"下，bgm.res扫描改动加入媒体库，作品URL：E:/ACG/Anime\test，点击打开文件夹依然出现问题。
> 
> 以上所有情况，打开文件夹都会进入"C:\Users\用户名\Documents"目录。

查到问题了，我写正则匹配的时候把斜杠搞反了😂感谢反馈，这两个问题已经在新发布的小更新内修复
